---
- hosts: "{{ target_hosts}}"
  gather_facts: no 
  become: yes

  vars:
    source_folder: /root/certs/
    destin_folder: C:\temp\

  tasks:
        - name: Gatherhost name
          win_shell: Write-host "$env:computername -Nonewline"
          register: hostName
        - name: Copy private SCOM sert to remote host
          win_copy:
            src: {{ source_folder }}{{ hostName }}.pfx
            dest: {{ destin_folder }}{{ hostName }}.pfx 
        - name: Copy Primark cert to remote host
          win_copy:
            src: {{ source_folder }}Primark.ie.cer
            dest: {{ destin_folder }}Primark.ie.cer
        - name: Execute SCOM register scipt
          win_shell: |
                  Import-Module PKI
                  $hostname = [System.Net.Dns]::GetHostName()
                  $pfx = $hostname + '.pfx'
                  $pfxPath = 'C:\temp\' + $pfx
                  $cerPath = 'C:\temp\Primark.ie.cer'
                  $expPfx = $hostname + '_x.pfx'
                  $expPfxPath = 'C:\temp\' + $expPfx
                  $appPath = 'C:\opt\app\fujitsu-scom-agent\MOMCertImport.exe'
                  try{
                          $pass = "scom" | ConvertTo-SecureString -AsPlainText -Force
                          Import-PfxCertificate -FilePath $pfxPath -Exportable -CertStoreLocation Cert:\LocalMachine\My -Password $pass -ErrorAction Stop
                          $password = $pass
                  }
                  catch{
                          $pass = "P@ssw0rd" | ConvertTo-SecureString -AsPlainText -Force
                          Import-PfxCertificate -FilePath $pfxPath -Exportable -CertStoreLocation Cert:\LocalMachine\My -Password $pass -ErrorAction Stop
                          $password = $pass
                  }
                  Import-Certificate -FilePath $cerPath -CertStoreLocation Cert:\LocalMachine\Root
                  $cert=GCI -Path Cert:\LocalMachine\My | Where-Object {($_.Subject -match $hostname) -and ($_.Issuer -notmatch 'FujitsuRoot')}
                  Get-variable -Name password |convertto-securestring -force -ASplainText
                  Export-PfxCertificate -Cert $cert -ChainOption EndEntityCertOnly -FilePath $expPfxPath -Password $password
                  Start-Sleep -Seconds 2
                  $pwd =  [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($password))
                  C:\opt\app\fujitsu-scom-agent\MOMCertImport.exe $expPfxPath /Password $pwd
                  Get-Service "HealthService" | Restart-service -Force

                  $registry=Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft Operations Manager\3.0\Machine Settings" |Select-Object -ExpandProperty ChannelCertificateHash
                  $sn=GCI -Path Cert:\LocalMachine\My | Where-Object {($_.Subject -match $env:COMPUTERNAME) -and ($_.Issuer -notmatch "FujitsuRoot")}; 
                  Write-host "Please compare 2 strings below. They should be simular"
                  Write-host "Registry key - $regisry"
                  Write-host "Vault    key - $sn.thumbprint
          register: regisry
        - name: execute AddScommanagemt gropu script
          win_shell: |
                    Param(
            [Parameter(Mandatory=$false)]
            [string]$ManagementServer = "IECWXWVPOMX001.Primark.local",

            [Parameter(Mandatory=$false)]
            [string]$MGMTGroupName = "Primark_SCOM",

            [Parameter(Mandatory=$false)]
            [int]$Port = "5723"
          )

          $ErrorActionPreference='Stop'

          Write-Warning "This will restart the agents health service"

          #Adding MG to the agent
          try{
          $Agent = New-Object -ComObject AgentConfigManager.MgmtSvcCfg
          $Agent.AddManagementGroup("$MGMTGroupName", "$ManagementServer", "$Port")}

          catch{
          CLS
          Write-host "An error occured please se exeption message:"

          Write-error $_.Exception.Message
          BREAK
          }

          get-service HealthService | Restart-Service

          Write-Host "Agent connected to the following management groups"
          $Agent.GetManagementGroups()
     

        - name: Display output
          debug:
            msg: {{ registry.stdout_lines }}}