---
- hosts: "{{ target_hosts}}"
  gather_facts: no 
  become: yes

  vars:
    source_folder: /root/certs/
    destin_folder: C:\temp\

  tasks:
        - name: Copy private SCOM sert to remote host
          win_copy:
            src: {{ source_folder }}{{ ansible_hostname }}.pfx
            dest: {{ destin_folder }}{{ ansible_hostname }}.pfx 
        - name: Copy Primark cert to remote host
          win_copy:
            src: {{ source_folder }}Primark.ie.cer
            dest: {{ destin_folder }}Primark.ie.cer
        - name: Execute script  on remote host
          win_shell: |
                  Import-Module PKI
                  $hostname = [System.Net.Dns]::GetHostName()
                  $pfx = $hostname + '.pfx'
                  $pfxPath = 'C:\temp\' + $pfx
                  $cerPath = 'C:\temp\Primark.ie.cer'
                  $expPfx = $hostname + '_x.pfx'
                  $expPfxPath = 'C:\temp\' + $expPfx
                  $appPath = 'C:\opt\app\fujitsu-scom-agent\MOMCertImport.exe'
                  try{
                          $pass = "scom" | ConvertTo-SecureString -AsPlainText -Force
                          Import-PfxCertificate -FilePath $pfxPath -Exportable -CertStoreLocation Cert:\LocalMachine\My -Password $pass -ErrorAction Stop
                          $password = $pass
                  }
                  catch{
                          $pass = "P@ssw0rd" | ConvertTo-SecureString -AsPlainText -Force
                          Import-PfxCertificate -FilePath $pfxPath -Exportable -CertStoreLocation Cert:\LocalMachine\My -Password $pass -ErrorAction Stop
                          $password = $pass
                  }
                  Import-Certificate -FilePath $cerPath -CertStoreLocation Cert:\LocalMachine\Root
                  $cert=GCI -Path Cert:\LocalMachine\My | Where-Object {($_.Subject -match $hostname) -and ($_.Issuer -notmatch 'FujitsuRoot')}
                  Get-variable -Name password |convertto-securestring -force -ASplainText
                  Export-PfxCertificate -Cert $cert -ChainOption EndEntityCertOnly -FilePath $expPfxPath -Password $password
                  Start-Sleep -Seconds 2
                  $pwd =  [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($password))
                  C:\opt\app\fujitsu-scom-agent\MOMCertImport.exe $expPfxPath /Password $pwd
        - name: Gathering info about cerfificate from registry
          win_shell: |
                  $registry=Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft Operations Manager\3.0\Machine Settings" |Select-Object -ExpandProperty ChannelCertificateHash
                  $sn=GCI -Path Cert:\LocalMachine\My | Where-Object {($_.Subject -match $env:COMPUTERNAME) -and ($_.Issuer -notmatch "FujitsuRoot")}; 
                  Write-host $regisry
                  Write-host $sn.thumbprint
          register: regisry
      
        - name: Display output
          debug:
            msg: {{ registry.stdout_lines }}}